### ISSUE TITLE
Stopped working after last update

### ISSUE THREAD

**Issue by jurgenhaas** [r-renato/ha-climacell-weather#57]
I had the climacell setup configured in yaml and it worked pretty well. But after the latest update I'm getting the following error in the logs rights after HA restart:

```
2021-03-10 08:52:10 ERROR (MainThread) [homeassistant.components.sensor] climacell: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 465, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/climacell/sensor.py", line 411, in update
    self._state = self.__valuemap[str(self._state)]
KeyError: '0.86'
```

This can be reproduced and happens every time I'm restarting HA.

Then I thought I should probably switch to the UI config and removed CC from the yaml config, restarted HA and went to config / integrations to add CC there. A popup shows up telling me about a config_flow error. When looking into the logs, I'm seeing this error message:

```
ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration climacell: No module named 'custom_components.climacell.config_flow'
```

Is that a known issue? What can I do to get back to a working version? Or can I provide more background information to further analyze the problem?

**Comment by testorp** [comment]
same here, this happened after the last HA update

core-2021.3.3
supervisor-2021.03.4
Home Assistant OS 5.12

**Comment by mrneilix** [comment]
I think it's because of the new climacell integration HASS has now. There's a naming conflict between them
