### ISSUE TITLE
Platform error sensor.climacell - Integration 'climacell' not found

### ISSUE THREAD

**Issue by SackOHammers** [r-renato/ha-climacell-weather#76]
After copying the files to homeassistant/custom_components/climacell and then saving the example setup into my configuration.yaml file,
I get an error when restarting HomeAssistant.  The only way I can get it to restart is to delete the climacell configuration out of my configuration.yaml file.

yaml configuration:
```
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
# Weather climatecell.co
  - platform: climacell
    api_key: "redacted"
    name: climacell
    latitude: "redacted"
    longitude: "redacted"
    units: us
    timelines:
      - name: "RR" #Realtime
        timestep: "1m"
        forecast_observations: 1
        fields:
          - temperatureMax
          - feels_like
          - humidity
          - wind_speed
          - wind_direction
          - wind_gust
          - pressure
          - precipitationIntensity
          - precipitation_type
          - visibility
          - cloud_cover
          - weather_condition
          - pm25
          - pm10
          - o3
          - no2
          - co
          - so2
          - epa_aqi
          - epa_health_concern
          - pollen_tree
          - pollen_weed
          - pollen_grass
          - fire_index
        update: auto
        scan_interval:
          # At least one of these must be specified:
          days: 0
          hours: 1
          minutes: 0
          seconds: 0
          milliseconds: 0
        exclude_interval:
          1:
            - "00:00"
            - "07:00"
      - name: "" #Daily
        timestep: "1d"
        forecast_observations: 5
        fields:
          - temperature
          - temperatureMin
          - temperatureMax
          - precipitationIntensityMin
          - precipitationIntensityMax
          - precipitation_probability
          - weather_condition
        scan_interval:
          # At least one of these must be specified:
          days: 0
          hours: 4
          minutes: 0
          seconds: 0
          milliseconds: 0
        exclude_interval:
          1:
            - "23:00"
            - "06:30"
```

Error:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:230
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:28:29 PM (1 occurrences)
Last logged: 8:28:29 PM

[140199916173888] The system cannot restart because the configuration is not valid: Platform error sensor.climacell - Integration 'climacell' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 986, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 191, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error sensor.climacell - Integration 'climacell' not found.
```

**Comment by denveronly** [comment]
Same error on my HA instance. 
I see in integrations list Climacell integration but unable to add it from integrations tab, i need to do it in text.

When i add it in text in config yaml i get error on reboot attempt
Platform error sensor.climacell - Integration 'climacell' not found.

It reacts as there is no integration i am trying to add a platform to
